name: customer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  app_links: ^6.1.1
  awesome_snackbar_content: ^0.1.3
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  custom_radio_grouped_button: ^2.2.1
  dart_ipify: ^1.1.1
  device_info_plus: ^9.0.0
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  external_app_launcher: ^4.0.0
  firebase_analytics: ^10.10.7
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
  firebase_remote_config: ^4.4.7
  firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.0.0+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_timer_countdown: ^1.0.7
  fluttertoast: ^8.2.5
  gauge_indicator: ^0.4.3
  geocoding: ^3.0.0
  geolocator: ^9.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  internet_file: ^1.2.0
  intl: ^0.18.1
  keyboard_dismisser: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  loader_overlay: ^4.0.0
  location: ^6.0.2
  logger: ^2.3.0
  marquee: ^2.2.3
  media_info:
    git:
      url: https://github.com/dharambudh1/flutter_plugin_media_info.git
  mime: ^1.0.5
  overlay_support: ^2.1.0
  package_info_plus: ^8.0.0
  page_view_dot_indicator: ^2.3.0
  path: ^1.9.0
  pdfx: ^2.6.0
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  pinput: ^4.0.0
  place_picker: ^0.10.0
  pod_player: ^0.2.0
  smart_auth: ^2.0.0
  syncfusion_flutter_sliders: 25.2.4
  transparent_image: ^2.0.1
  upgrader: ^10.3.0
  url_launcher: ^6.2.6
  video_thumbnail:
    git:
      url: https://github.com/dharambudh1/video_thumbnail.git

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
